import { Metadata } from "next";



export const metadata : Metadata = {
  title: {
    absolute:"",
    default:"NextJs Practice", // for global and child without their own metadata
    template:"",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={
            {
              backgroundColor: "lightblue",
              padding: "1rem",
            }
          }
        >
          <p>Header is Here</p>
        </header>
        {children}

        <footer
          style={{
            backgroundColor: "beige",
            padding: "1rem"
          }}
        >
          <p>Footer is Here</p>
        </footer>
      </body>
    </html>
  )
}
