import { Metadata } from "next";
import Link from "next/link";



export const metadata : Metadata = {
  title: {
    absolute:"", //this one ignores the others mainly used in the child templates
    default:"NextJs Practice", // for global and child without their own metadata
    template:"%s - Dabral NextJS Test",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>
            Header is Here | <Link href="/">Click here for Homepage</Link>
          </p>
        </header>
        {children}

        <footer
          style={{
            backgroundColor: "beige",
            padding: "1rem",
          }}
        >
          <p>Footer is Here</p>
        </footer>
      </body>
    </html>
  );
}
